apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-app
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: home-app
          image: swistek/test-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: home-app
  namespace: prod
spec:
  selector:
    app: home-app
  ports:
    - port: 80
      targetPort: 4173
