apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-app-prod
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: prod.marketzooo.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-app
                port:
                  number: 80
